app_url_shorten:
  path: /url/shorten
  controller: App\Controller\UrlController::shortenUrl

app_url_redirect:
  path: /url/redirect
  controller: App\Controller\UrlController::redirectWithShortenedUrl